import type { FirstPersonRigConfig } from "./types";
import kuptchiArmsUrl from "../assets/first-person-arms/kuptchi/FBX_Files/FP_Arms.fbx?url";
import kuptchiBasePoseUrl from "../assets/first-person-arms/kuptchi/FBX_Files/Animations/Rifle_01_Animations/Poses/FP_Arms_Rifle_01_BasePose.fbx?url";
import kuptchiBreathingUrl from "../assets/first-person-arms/kuptchi/FBX_Files/Animations/Rifle_01_Animations/Cycles/FP_Arms_Rifle_01_Breathing.fbx?url";
import kuptchiHideUrl from "../assets/first-person-arms/kuptchi/FBX_Files/Animations/Rifle_01_Animations/TransitionAnimations/FP_Arms_Rifle_01_Hide.fbx?url";
import kuptchiInteractUrl from "../assets/first-person-arms/kuptchi/FBX_Files/Animations/Rifle_01_Animations/OneTimeAnimations/FP_Arms_Rifle_01_Interact.fbx?url";
import kuptchiWalkUrl from "../assets/first-person-arms/kuptchi/FBX_Files/Animations/Rifle_01_Animations/Cycles/FP_Arms_Rifle_01_Walk.fbx?url";

export const FIRST_PERSON_RIG_CONFIG: FirstPersonRigConfig = {
  activeRigUrl: kuptchiArmsUrl,
  assetFormat: "fbx",
  visualReviewStatus: "failed",
  visualReviewNotes:
    "Disabled from the main first-person view after manual visual review: the Kuptchi FBX rendered with a tangled/reversed pose and dark materials in Office3D.",
  animationSources: [
    { action: "idle", url: kuptchiBreathingUrl },
    { action: "walk", url: kuptchiWalkUrl },
    { action: "jump", url: kuptchiBasePoseUrl },
    { action: "click", url: kuptchiInteractUrl },
    { action: "reach_mid", url: kuptchiInteractUrl },
    { action: "reach_high", url: kuptchiInteractUrl },
    { action: "pickup_floor", url: kuptchiInteractUrl },
    { action: "grab_shelf", url: kuptchiInteractUrl },
    { action: "hold_one_hand", url: kuptchiBasePoseUrl },
    { action: "hold_two_hand", url: kuptchiBasePoseUrl },
    { action: "put_away", url: kuptchiHideUrl },
    { action: "inspect", url: kuptchiBasePoseUrl },
  ],
  attribution: {
    title: "PSX-Weapons Assets [Free Pack] - FP Arms",
    author: "Kuptchi",
    url: "https://kuptchi.itch.io/f",
    license: "free-commercial-use-no-attribution-required",
    notes:
      "Free commercial-use first-person arms pack. Only the base arms and generic animation FBX files are bundled; weapon meshes are excluded.",
  },
  fallbackMode: "safe-placeholder-hands",
  generatedOfficeActions: false,
  rootTransform: {
    position: [0, -0.58, -0.72],
    rotation: [0, 0, 0],
    scale: 0.012,
  },
  socketMap: {
    leftPalm: ["hand_l", "hand.L", "Hand.L", "HandL", "LeftHand"],
    rightPalm: [
      "hand_r",
      "hand.R",
      "Hand.R",
      "HandR",
      "Hand.R.001",
      "HandR001",
      "RightHand",
      "hand_r",
    ],
    leftGrip: ["hand_l", "handIK.L", "hand.L", "Hand.L", "HandL", "LeftHand"],
    rightGrip: [
      "hand_r",
      "handIK.R",
      "hand.R",
      "Hand.R",
      "HandR",
      "Hand.R.001",
      "HandR001",
      "RightHand",
      "hand_r",
    ],
    leftWrist: [
      "lowerarm_l",
      "forearm_l",
      "forearm.L",
      "LowerArm.L",
      "LowerArmL",
      "LeftForeArm",
      "forearm_l",
    ],
    rightWrist: [
      "lowerarm_r",
      "forearm_r",
      "forearm.R",
      "LowerArm.R",
      "LowerArmR",
      "LowerArm.R.001",
      "LowerArmR001",
      "RightForeArm",
      "forearm_r",
    ],
    heldItem: [
      "hand_r",
      "handIK.R",
      "hand.R",
      "Hand.R",
      "HandR",
      "Hand.R.001",
      "HandR001",
      "RightHand",
    ],
    chest: [
      "spine_03",
      "spine_02",
      "spine_01",
      "Chest",
      "Spine",
      "Spine1",
      "Torso",
      "root",
      "RootNode",
    ],
    cameraAnchor: [
      "camera",
      "root",
      "ArmsRig",
      "Armature",
    ],
  },
  animationMap: {
    idle: ["idle"],
    walk: ["walk"],
    jump: ["jump"],
    click: ["click"],
    reach_mid: ["reach_mid", "click"],
    reach_high: ["reach_high", "click"],
    pickup_floor: ["pickup_floor", "click"],
    grab_shelf: ["grab_shelf", "click"],
    hold_one_hand: ["hold_one_hand"],
    hold_two_hand: ["hold_two_hand", "hold_one_hand"],
    put_away: ["put_away"],
    inspect: ["inspect", "hold_one_hand"],
    reach: ["reach_mid", "click"],
    grab: ["grab_shelf", "click"],
    press: ["click"],
    point: ["click"],
    holdItem: ["hold_one_hand"],
    putAway: ["put_away"],
  },
};
